FROM python:3.12-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.9.8 /uv /uvx /bin/

WORKDIR /app 

ENV PYTHONPATH=

COPY backend backend

RUN uv pip install --system -r requirements.txt

COPY . . 

EXPOSE 8001 

CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8001"]
